### ISSUE TITLE
i run npm install then npm start but i get error !

### ISSUE THREAD

**Issue by Bhavye-Malhotra** [instafluff/DetectivePawsome#1]
Pls tell how to setup this game locally! :)

**Comment by patrik-herman** [comment]
Hi! Assuming you've already installed node.js, locate the folder in your CMD, and run `node index.js` from there. If you get a missing "webwebweb" module, simply run `npm install webwebweb` and try again :) If WebWebWeb starts successfully, head over to [http://localhost:9834/](http://localhost:9834/) to play it :)

**Comment by Bhavye-Malhotra** [comment]
Thanks, It Works Now !

**Comment by Bhavye-Malhotra** [comment]
Another thing how can i host this on heroku or netlify! :) I made some changes u know want my friends review it

**Comment by Bhavye-Malhotra** [comment]
Nvm i got it :P
